sudo: required

services:
  - docker

before_install:
  - docker-compose -f docker-compose.develop.yml up -d

script:
  - docker exec -it block-producers-directory-back bash -c "radon cc directory -nb --total-average"
  - docker exec -it block-producers-directory-back bash -c "cat requirements/dev.txt requirements/project.txt requirements/tests.txtt | safety check --stdin"
  - docker exec -it block-producers-directory-back bash -c "bash <(curl -s https://linters.io/sort-requirements) requirements/dev.txt requirements/project.txt requirements/tests.txt"
  - docker exec -it block-producers-directory-back bash -c "isort -rc directory --diff"
  - docker exec -it block-producers-directory-back bash -c "flake8 directory"
