version: '3'
services:

  bp-directory-back:
    container_name: bp-directory-back
    build:
      context: .
      dockerfile: Dockerfile.develop
    command: sh ops/development/start-server.sh
    depends_on:
      - postgres
    privileged: true
    volumes:
      - .:/bp-directory-back
      - ./shared:/bp-directory-back/shared
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true

  postgres:
    container_name: postgres
    image: postgres
    restart: always
